Tentando corrigir o hook script.

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -5,10 +5,10 @@
 
 set -e
 
-if [ -z $OPENSHIFT_DB_HOST ]
+if [ -z $OPENSHIFT_POSTGRESQL_DB_HOST ]
 then
     echo 1>&2
-    echo "Could not find database.  Please run:" 1>&2
+    echo "Could not find database." 1>&2
 #    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
 #    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
     echo 1>&2
@@ -16,12 +16,12 @@ then
 fi
 
 # Confirm database exists, if not create it
-if /usr/bin/psql -U "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -d "$OPENSHIFT_APP_NAME" -c "select 1;;" > /dev/null
+if /usr/bin/psql -U "$OPENSHIFT_POSTGRESQL_DB_USERNAME" --password="$OPENSHIFT_POSTGRESQL_DB_PASSWORD" -h "$OPENSHIFT_POSTGRESQL_DB_HOST" -d "$PGDATABASE" -c "select 1;;" > /dev/null
 then
     echo
 #    echo "Schema not found!  Importing schema from .openshift/action_hooks/redmine.sql"
 #    echo
-    /usr/bin/psql -U "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -d "$OPENSHIFT_APP_NAME" -f "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/script.sql" > "$OPENSHIFT_REPO_DIR/teste.txt"
+    /usr/bin/psql -U "$OPENSHIFT_POSTGRESQL_DB_USERNAME" --password="$OPENSHIFT_POSTGRESQL_DB_PASSWORD" -h "$OPENSHIFT_POSTGRESQL_DB_HOST" -d "$PGDATABASE" -f "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/script.sql" > "$OPENSHIFT_REPO_DIR/teste.txt"
     echo
     echo "done."
 # else
